repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=120]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=120]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        language: python
        args:
        - --no-strict-optional
        - --ignore-missing-imports
        - --scripts-are-modules
        - --allow-untyped-decorators
        - --strict
        - --explicit-package-bases
        - --namespace-packages
        exclude: web


-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      -  id: isort
         name: isort (python)
         args:
             - --profile=black
             - --line-length=120
